language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install libqt4-dev libqt4-qt3support
  - sudo apt-get install automake libtool gperf flex #bison

script:
  - uname -a
  - $CXX --version

  # Travis has Bison 2.5 --> You need at least version 2.6 of the 'bison' parse generator to use 'api.prefix' definitions.
  - wget http://ftp.gnu.org/gnu/bison/bison-2.6.tar.gz -O /tmp/bison-2.6.tar.gz
  - tar -xzvf /tmp/bison-2.6.tar.gz
  - cd bison-2.6 && ./configure --prefix=/usr && make && sudo make install && cd ..
  - bison --version

  # Build ADMS from release
  - wget http://sourceforge.net/projects/mot-adms/files/adms-source/2.3/adms-2.3.2.tar.gz -O /tmp/adms-2.3.2.tar.gz
  - tar -xzvf /tmp/adms-2.3.2.tar.gz
  - cd adms-2.3.2 && ./configure --prefix=/usr && make && sudo make install && cd ..
  - admsXml --version

  # build GUI components
  - cd qucs
  - sh autogen.sh
  - ./configure --enable-maintainer-mode
  - make
  - cd ..

  # build Qucs-ator
  - cd qucs-core
  - sh bootstrap.sh
  - ./configure --enable-maintainer-mode --with-mkadms=`which admsXml`
  - make
