language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install libqt4-dev libqt4-qt3support
  - sudo apt-get install automake libtool gperf flex #bison

  # Set xvfb for headless qucs GUI test
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - uname -a
  - $CXX --version

  # `sudo make install` fail with clang for ADMS, temporary workaround
  - export CC=`which $CC`
  - export CXX=`which $CXX`

  # Travis has Bison 2.5 --> You need at least version 2.6 of the 'bison' parse generator to use 'api.prefix' definitions.
  - wget http://ftp.gnu.org/gnu/bison/bison-2.6.tar.gz -O /tmp/bison-2.6.tar.gz
  - tar -xzvf /tmp/bison-2.6.tar.gz
  - cd bison-2.6 && ./configure --prefix=/usr && make && sudo make install && cd ..
  - bison --version

  # Build ADMS from release
  - wget http://sourceforge.net/projects/mot-adms/files/adms-source/2.3/adms-2.3.2.tar.gz -O /tmp/adms-2.3.2.tar.gz
  - tar -xzvf /tmp/adms-2.3.2.tar.gz
  - cd adms-2.3.2 && ./configure --prefix=/usr && make && sudo make install && cd ..
  - admsXml --version

  # build Qucs GUI components
  - cd qucs
  - ./autogen.sh
  - ./configure --enable-maintainer-mode --prefix=/usr
  - make && sudo make install
  - cd ..

  # build Qucs-core
  - cd qucs-core
  - ./bootstrap.sh
  - ./configure --enable-maintainer-mode --prefix=/usr --with-mkadms=`which admsXml`
  - make && sudo make install
  - cd ..

  # test installation
  - qucs -v
  - qucsator -v
