language: cpp

compiler:
  - gcc
  - clang

python:
  - "2.7"
virtualenv:
  system_site_packages: true

before_install:
  # We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # try newer gnu package
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo apt-get update -qq
  - sudo apt-get install build-essential
  - sudo apt-get install libqt4-dev libqt4-qt3support
  - sudo apt-get install automake libtool gperf flex bison
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  # We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

  # Set xvfb for headless qucs GUI test
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

  # Qucs-Test uses Numpy to compare results
  - sudo apt-get install -qq python-numpy

  # grab tip of Qucs-Test
  - git clone --depth=1 --branch=master git://github.com/Qucs/qucs-test.git qucs-test

script:
  - uname -a
  - $CXX --version
  - autoconf --version
  - automake --version
  - python --version
  - python -c "import numpy; print numpy.__version__"
  - pwd
  - ls

  # `sudo make install` fail with clang for ADMS, temporary workaround
  - export CC=`which $CC`
  - export CXX=`which $CXX`

  # Travis has Bison 2.5 --> You need at least version 2.6 of the 'bison' parse generator to use 'api.prefix' definitions.
  # - wget http://ftp.gnu.org/gnu/bison/bison-2.6.tar.gz -O /tmp/bison-2.6.tar.gz
  # - tar -xzvf /tmp/bison-2.6.tar.gz
  # - cd bison-2.6 && ./configure --prefix=/usr && make && sudo make install && cd ..
  - bison --version

  # Build ADMS from release (avoid need of Perl and its modules)
  - wget http://sourceforge.net/projects/mot-adms/files/adms-source/2.3/adms-2.3.4.tar.gz -O /tmp/adms-2.3.4.tar.gz
  - tar -xzvf /tmp/adms-2.3.4.tar.gz
  - cd adms-2.3.4 && ./configure --prefix=/usr && make && sudo make install && cd ..
  - admsXml --version

  # build Qucs GUI components
  - cd qucs
  - ./autogen.sh
  - ./configure --enable-maintainer-mode --prefix=/usr
  - make && sudo make install
  - cd ..

  # build Qucs-core
  - cd qucs-core
  - ./bootstrap.sh
  - ./configure --enable-maintainer-mode --prefix=/usr --with-mkadms=`which admsXml`
  - make && sudo make install && make check
  - cd ..

  # test installation
  - qucs -v
  - qucsator -v

  # run Qucs-Test suite
  # need to be on `script` section to raise error as failure
  - cd qucs-test && ./run.py --prefix /usr/bin/ --qucsator --skip skip.txt && cd ..
